-- Arkade -> EVM swaps table (chain-agnostic endpoint)
CREATE TABLE IF NOT EXISTS arkade_to_evm_swaps (
    swap_id TEXT PRIMARY KEY NOT NULL,
    status TEXT NOT NULL,
    fee_sats INTEGER NOT NULL,
    hash_lock TEXT NOT NULL,
    source_token TEXT NOT NULL,
    target_token TEXT NOT NULL,
    created_at TEXT NOT NULL,
    chain TEXT NOT NULL,
    evm_chain_id INTEGER NOT NULL,
    target_token_address TEXT NOT NULL,
    target_token_symbol TEXT NOT NULL,
    target_token_decimals INTEGER NOT NULL,
    btc_expected_sats INTEGER NOT NULL,
    evm_expected_sats INTEGER NOT NULL,
    target_token_amount INTEGER,
    btc_vhtlc_address TEXT NOT NULL,
    btc_fund_txid TEXT,
    btc_claim_txid TEXT,
    evm_htlc_address TEXT NOT NULL,
    evm_coordinator_address TEXT NOT NULL,
    client_evm_address TEXT NOT NULL,
    server_evm_address TEXT NOT NULL,
    evm_fund_txid TEXT,
    evm_claim_txid TEXT,
    evm_refund_locktime INTEGER NOT NULL,
    sender_pk TEXT NOT NULL,
    receiver_pk TEXT NOT NULL,
    arkade_server_pk TEXT NOT NULL,
    vhtlc_refund_locktime INTEGER NOT NULL,
    unilateral_claim_delay INTEGER NOT NULL,
    unilateral_refund_delay INTEGER NOT NULL,
    unilateral_refund_without_receiver_delay INTEGER NOT NULL,
    network TEXT NOT NULL,
    -- SwapParams
    secret_key TEXT NOT NULL,
    public_key TEXT NOT NULL,
    preimage TEXT NOT NULL,
    preimage_hash TEXT NOT NULL,
    user_id TEXT NOT NULL,
    key_index INTEGER NOT NULL
);
