#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src", "version.ts");

const contents = `// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on \`npm version\` and \`npm run build\`.
export const SDK_NAME = "${pkg.name.replace(/^@[^/]+\//, "")}";
export const SDK_VERSION = "${pkg.version}";
export const CLIENT_AGENT = \`\${SDK_NAME}/\${SDK_VERSION}\`;
`;

writeFileSync(target, contents);
console.log(`✓ src/version.ts synced to ${pkg.version}`);
